---
include:
  - board: corne_left
  shield: corne_left
#    shield: nice_view
    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: corne_right
  shield: corne_right
#    shield: nice_view
    #snippet: zmk-usb-logging
#  - board: eyelash_corne_left
#    shield: nice_view
#    snippet: studio-rpc-usb-uart
#    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
#    artifact-name: eyelash_corne_studio_left
#  - board: nice_nano_v2
#    shield: settings_reset
    #snippet: zmk-usb-logging
 
